# Generated by Django 4.2.2 on 2023-06-26 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0ef08819-75c4-43f0-9bf1-d83ce199a576'), primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('num_floors', models.PositiveIntegerField()),
                ('num_lifts', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
