# Generated by Django 4.2.2 on 2023-06-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator', '0003_elevator_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.IntegerField(choices=[(1, 'UP'), (2, 'DOWN'), (3, 'STOP'), (4, 'MAINTENANCE')], default=3),
        ),
    ]
